const contact = "https://wa.me/5511982129999?text=Olá,%20quero%20entender%20melhor%20o%20Nas%20Rocas%20Club.";
function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  return <main id="top">
    <header className="site-header"><a className="brand-header" href="#top" aria-label="Resid — início"><img src="resid-logo.png" alt="Resid" /></a><nav aria-label="Navegação principal"><a href="#clube">O clube</a><a href="#comunidade">Comunidade</a><a href="#valorizacao">Valorização</a></nav><a className="header-cta" href={contact}>Quero ser membro <Arrow /></a></header>
    <section className="hero guide-hero" aria-labelledby="hero-title"><img className="hero-image" src="nas-rocas-home-dji0877.jpg" alt="Ilha Rasa, Búzios — Nas Rocas Club — o destino está de volta" /><div className="hero-wash" aria-hidden="true" /><div className="hero-content"><p className="eyebrow">ILHA RASA · BÚZIOS · RJ</p><h1 id="hero-title">O Nas Rocas<br /><em>está de volta.</em></h1><div className="hero-intro"><strong>Um lugar para quem reconhece o valor dos encontros, do tempo e do mar.</strong><span>Esta é uma forma de conhecer Búzios pelo olhar Resid — e compartilhar com quem também gosta de viver as coisas com mais intenção.</span></div><a className="pill-link" href={contact}><span>Conversar com o Concierge</span><Arrow /></a></div></section>
    <section className="guide-section" id="momento"><div className="guide-heading"><span>01</span><div><p className="kicker">O MOMENTO</p><h2>Pertencer a algo raro<br /><em>começa com uma escolha.</em></h2></div></div><div className="chapter-copy"><p>O Nas Rocas Club está prestes a abrir, e a comunidade que escolheu viver essa realidade já está quase completa.</p><p>150 membros já fazem parte desse começo. Restam poucas oportunidades antes da inauguração oficial — um convite para chegar no primeiro capítulo, com tempo e presença.</p><a className="guide-cta" href={contact}>Conversar sobre o membership <Arrow /></a></div></section>
    <section className="guide-section" id="manifesto"><div className="image-interlude"><img src="nas-rocas-hospitalidade-real.jpg" alt="Búzios — o destino está de volta" /></div><div className="chapter-copy"><p>Existe uma Búzios que muita gente guarda na memória: encontros verdadeiros, liberdade e uma energia muito própria daquele pedaço de Brasil.</p><p>Essa memória nunca desapareceu. Estava apenas esperando o momento certo para voltar.</p><p>O Nas Rocas (re)nasce com essa sensação — uma versão mais íntima, cuidadosa e especial de viver Búzios.</p><a className="guide-cta" href={contact}>Conhecer este novo capítulo <Arrow /></a></div></section>
    <section className="guide-section dining-section" id="clube"><div className="guide-heading light"><span>02</span><div><p className="kicker">O CLUBE</p><h2>Um destino icônico.<br /><em>O Nas Rocas Club.</em></h2></div></div><div className="benefit-grid"><article className="benefit-card"><h3>Um clube privado</h3><p>Uma comunidade que se reconhece, um calendário vivo de experiências e um novo ritmo de vida.</p></article><article className="benefit-card"><h3>Marcos do projeto</h3><p><strong>2022</strong> Idealização e aquisição da Ilha Rasa.<br /><strong>2023</strong> Desenvolvimento dos projetos.<br /><strong>2025</strong> Licenciamento e início das obras.<br /><strong>2026</strong> Inauguração oficial.</p></article></div></section>
    <section className="guide-section" id="comunidade"><div className="guide-heading"><span>03</span><div><p className="kicker">COMUNIDADE</p><h2>O Nas Rocas Club<br /><em>não é para todo mundo.</em></h2></div></div><div className="chapter-copy"><p>É para quem entende o valor do tempo, dos encontros e dos lugares certos.</p><p>Uma comunidade que não precisa se explicar. As pessoas se reconhecem pelo jeito de olhar para a vida.</p><a className="guide-cta" href={contact}>Conversar com o Concierge <Arrow /></a></div></section>
    <section className="guide-section dining-section" id="valorizacao"><div className="guide-heading light"><span>04</span><div><p className="kicker">PATRIMÔNIO VIVO</p><h2>Quem decide agora encontra<br /><em>um jeito raro de pertencer.</em></h2></div></div><div className="chapter-copy"><p>O membership do Nas Rocas Club acompanha a qualidade de vida da família e a possibilidade de construir memórias em um lugar pensado para durar.</p><div className="benefit-grid"><article className="benefit-card"><h3>Entrada pré-inauguração</h3><p>Uma janela especial para conhecer o clube desde o primeiro capítulo.</p></article><article className="benefit-card"><h3>Condições para fundadores</h3><p>Condições pensadas para quem chega antes da inauguração oficial.</p></article><article className="benefit-card"><h3>Um lugar para voltar</h3><p>Um patrimônio de experiências, encontros e tempo bem vivido.</p></article></div><a className="guide-cta" href={contact}>Conversar sobre o clube <Arrow /></a></div></section>
    <section className="guide-section" id="contato"><div className="guide-heading"><span>05</span><div><p className="kicker">MEMBERSHIP</p><h2>Uma comunidade seleta,<br /><em>com o mesmo propósito de vida.</em></h2></div></div><div className="chapter-copy"><p>Um ciclo de entrada que se aproxima do encerramento, sem pressa e sem promessa exagerada.</p><p>Se esse jeito de viver Búzios fizer sentido para você, converse com nosso Concierge e conheça o que o Nas Rocas reserva.</p><a className="guide-cta" href={contact}>Conversar com o Concierge <Arrow /></a></div></section>
    <footer><span className="footer-logo"><img src="resid-logo.png" alt="Resid" /></span><p>RESID CLUB & HOTELS · NAS ROCAS CLUB · ILHA RASA, BÚZIOS — RJ</p><a href="#top">Voltar ao topo ↑</a></footer>
  </main>;
}
