const contact = "https://wa.me/5511982129999?text=Olá,%20quero%20entender%20melhor%20o%20Nas%20Rocas%20Club.";
function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  return <main id="top">
    <header className="site-header"><a className="brand-header" href="#top" aria-label="Resid — início"><img src="resid-logo.png" alt="Resid" /></a><nav aria-label="Navegação principal"><a href="#clube">O clube</a><a href="#comunidade">Comunidade</a><a href="#valorizacao">Valorização</a></nav><a className="header-cta" href={contact}>Quero ser membro <Arrow /></a></header>
    <section className="hero guide-hero" aria-labelledby="hero-title"><img className="hero-image" src="nas-rocas-home-dji0877.jpg" alt="Ilha Rasa, Búzios — Nas Rocas Club — o destino está de volta" /><div className="hero-wash" aria-hidden="true" /><div className="hero-content"><p className="eyebrow">ILHA RASA · BÚZIOS · RJ</p><h1 id="hero-title">O Nas Rocas<br /><em>está de volta.</em></h1><div className="hero-intro"><strong>ACESSO RESTRITO A UMA COMUNIDADE QUE SE RECONHECE</strong><span>Um destino icônico, uma comunidade seleta e um novo ritmo de vida à beira-mar.</span></div><a className="pill-link" href={contact}><span>Descubra como fazer parte</span><Arrow /></a></div></section>
    <section className="guide-section" id="momento"><div className="guide-heading"><span>01</span><div><p className="kicker">O MOMENTO</p><h2>Pertencer a algo raro<br /><em>começa com uma escolha.</em></h2></div></div><div className="chapter-copy"><p>O Nas Rocas Club está prestes a abrir, e a comunidade que pertence a essa realidade já está quase completa.</p><p>150 membros já garantiram seu ingresso a esse mundo. Concedemos mais 30 oportunidades antes da inauguração oficial.</p><a className="guide-cta" href={contact}>Quero garantir meu membership <Arrow /></a></div></section>
    <section className="guide-section" id="manifesto"><div className="image-interlude"><img src="nas-rocas-hospitalidade-real.jpg" alt="Búzios — o destino está de volta" /></div><div className="chapter-copy"><p>Existe uma Búzios que muita gente guarda na memória. Uma época de encontros verdadeiros, liberdade e uma energia muito própria daquele pedaço de Brasil.</p><p>Essa memória nunca desapareceu. Estava esperando o momento certo para voltar.</p><p>O Nas Rocas (re)nasce, e com ele a melhor versão de Búzios, de forma única e exclusiva, assim como você!</p><a className="guide-cta" href={contact}>Garanta seu acesso a esse novo capítulo <Arrow /></a></div></section>
    <section className="guide-section dining-section" id="clube"><div className="guide-heading light"><span>02</span><div><p className="kicker">O CLUBE</p><h2>Um destino icônico.<br /><em>O Nas Rocas Club.</em></h2></div></div><div className="benefit-grid"><article className="benefit-card"><h3>Um clube privado</h3><p>Uma comunidade que se reconhece, um calendário vivo de experiências e um novo ritmo de vida.</p></article><article className="benefit-card"><h3>Marcos do projeto</h3><p><strong>2022</strong> Idealização e aquisição da Ilha Rasa.<br /><strong>2023</strong> Desenvolvimento dos projetos.<br /><strong>2025</strong> Licenciamento e início das obras.<br /><strong>2026</strong> Inauguração oficial.</p></article></div></section>
    <section className="guide-section" id="comunidade"><div className="guide-heading"><span>03</span><div><p className="kicker">COMUNIDADE</p><h2>O Nas Rocas Club<br /><em>não é para todo mundo.</em></h2></div></div><div className="chapter-copy"><p>É para quem entende o valor do tempo, dos encontros e dos lugares certos.</p><p>Uma comunidade que não anuncia. Reconhece.</p><a className="guide-cta" href={contact}>Quero fazer parte <Arrow /></a></div></section>
    <section className="guide-section dining-section" id="valorizacao"><div className="guide-heading light"><span>04</span><div><p className="kicker">PATRIMÔNIO VIVO</p><h2>Quem decide agora garante<br /><em>exclusividade e pertencimento.</em></h2></div></div><div className="chapter-copy"><p>O membership do Nas Rocas Club é um investimento na qualidade de vida de toda a família e um ativo patrimonial que se valoriza ao longo do tempo.</p><div className="benefit-grid"><article className="benefit-card"><h3>Entrada pré-inauguração</h3><p>O preço mais baixo que o Nas Rocas Club jamais terá. Uma janela única.</p></article><article className="benefit-card"><h3>Condições especiais</h3><p>Facilidades de pagamento exclusivas para membros fundadores.</p></article><article className="benefit-card"><h3>Last call</h3><p>Após a inauguração, as condições pré-operacionais serão encerradas definitivamente.</p></article></div><a className="guide-cta" href={contact}>Quero fazer parte desta comunidade <Arrow /></a></div></section>
    <section className="guide-section" id="contato"><div className="guide-heading"><span>05</span><div><p className="kicker">MEMBERSHIP</p><h2>Uma comunidade seleta,<br /><em>com o mesmo propósito de vida.</em></h2></div></div><div className="chapter-copy"><p>Um ciclo de entrada que se aproxima do encerramento.</p><p>Entre em contato com nosso concierge e descubra o que o Nas Rocas reserva para você e sua família.</p><a className="guide-cta" href={contact}>Conversar com o Concierge <Arrow /></a></div></section>
    <footer><span className="footer-logo"><img src="resid-logo.png" alt="Resid" /></span><p>RESID CLUB & HOTELS · NAS ROCAS CLUB · ILHA RASA, BÚZIOS — RJ</p><a href="#top">Voltar ao topo ↑</a></footer>
  </main>;
}
